modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MPL2.0"
issueTrackerURL=""
[[mods]]
modId="gravelmon"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="icon.png"
description='''${mod_description}'''
[[dependencies.gravelmon]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.gravelmon]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
#[[dependencies.gravelmon]]
#modId="cobblemon"
#mandatory=true
#versionRange="[1.5.2,)"
#ordering="NONE"
#side="BOTH"
[[dependencies.gravelmon]]
modId="packetfixer"
mandatory=true
versionRange="[1.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.gravelmon]]
modId="gravels_extended_battles"
mandatory=true
versionRange="[1.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.gravelmon]]
modId="architectury"
mandatory=true
versionRange="[9.1.10,)"
ordering="NONE"
side="BOTH"